var routes = {
   "mode_name":"Bus",
   "route":[
      {
         "route_id":"701",
         "route_name":"CT1"
      },
      {
         "route_id":"747",
         "route_name":"CT2"
      },
      {
         "route_id":"708",
         "route_name":"CT3"
      },
      {
         "route_id":"741",
         "route_name":"Silver Line SL1"
      },
      {
         "route_id":"742",
         "route_name":"Silver Line SL2"
      },
      {
         "route_id":"751",
         "route_name":"Silver Line SL4"
      },
      {
         "route_id":"749",
         "route_name":"Silver Line SL5"
      },
      {
         "route_hide":"true",
         "route_id":"746",
         "route_name":"Silver Line Waterfront"
      },
      {
         "route_id":"1",
         "route_name":"1"
      },
      {
         "route_id":"4",
         "route_name":"4"
      },
      {
         "route_id":"5",
         "route_name":"5"
      },
      {
         "route_id":"7",
         "route_name":"7"
      },
      {
         "route_id":"8",
         "route_name":"8"
      },
      {
         "route_id":"9",
         "route_name":"9"
      },
      {
         "route_id":"10",
         "route_name":"10"
      },
      {
         "route_id":"11",
         "route_name":"11"
      },
      {
         "route_id":"14",
         "route_name":"14"
      },
      {
         "route_id":"15",
         "route_name":"15"
      },
      {
         "route_id":"16",
         "route_name":"16"
      },
      {
         "route_id":"17",
         "route_name":"17"
      },
      {
         "route_id":"18",
         "route_name":"18"
      },
      {
         "route_id":"19",
         "route_name":"19"
      },
      {
         "route_id":"21",
         "route_name":"21"
      },
      {
         "route_id":"22",
         "route_name":"22"
      },
      {
         "route_id":"23",
         "route_name":"23"
      },
      {
         "route_id":"24",
         "route_name":"24"
      },
      {
         "route_hide":"true",
         "route_id":"2427",
         "route_name":"24/27"
      },
      {
         "route_id":"26",
         "route_name":"26"
      },
      {
         "route_id":"27",
         "route_name":"27"
      },
      {
         "route_id":"28",
         "route_name":"28"
      },
      {
         "route_id":"29",
         "route_name":"29"
      },
      {
         "route_id":"30",
         "route_name":"30"
      },
      {
         "route_id":"31",
         "route_name":"31"
      },
      {
         "route_id":"32",
         "route_name":"32"
      },
      {
         "route_hide":"true",
         "route_id":"3233",
         "route_name":"32/33"
      },
      {
         "route_id":"33",
         "route_name":"33"
      },
      {
         "route_id":"34",
         "route_name":"34"
      },
      {
         "route_id":"34E",
         "route_name":"34E"
      },
      {
         "route_id":"35",
         "route_name":"35"
      },
      {
         "route_id":"36",
         "route_name":"36"
      },
      {
         "route_id":"37",
         "route_name":"37"
      },
      {
         "route_hide":"true",
         "route_id":"3738",
         "route_name":"37/38"
      },
      {
         "route_id":"38",
         "route_name":"38"
      },
      {
         "route_id":"39",
         "route_name":"39"
      },
      {
         "route_id":"40",
         "route_name":"40"
      },
      {
         "route_hide":"true",
         "route_id":"4050",
         "route_name":"40/50"
      },
      {
         "route_id":"41",
         "route_name":"41"
      },
      {
         "route_id":"42",
         "route_name":"42"
      },
      {
         "route_id":"43",
         "route_name":"43"
      },
      {
         "route_id":"44",
         "route_name":"44"
      },
      {
         "route_id":"45",
         "route_name":"45"
      },
      {
         "route_id":"47",
         "route_name":"47"
      },
      {
         "route_id":"50",
         "route_name":"50"
      },
      {
         "route_id":"51",
         "route_name":"51"
      },
      {
         "route_id":"52",
         "route_name":"52"
      },
      {
         "route_id":"55",
         "route_name":"55"
      },
      {
         "route_id":"57",
         "route_name":"57"
      },
      {
         "route_id":"57A",
         "route_name":"57A"
      },
      {
         "route_id":"59",
         "route_name":"59"
      },
      {
         "route_id":"60",
         "route_name":"60"
      },
      {
         "route_id":"62",
         "route_name":"62"
      },
      {
         "route_hide":"true",
         "route_id":"627",
         "route_name":"62/76"
      },
      {
         "route_id":"64",
         "route_name":"64"
      },
      {
         "route_id":"65",
         "route_name":"65"
      },
      {
         "route_id":"66",
         "route_name":"66"
      },
      {
         "route_id":"67",
         "route_name":"67"
      },
      {
         "route_id":"68",
         "route_name":"68"
      },
      {
         "route_id":"69",
         "route_name":"69"
      },
      {
         "route_id":"70",
         "route_name":"70"
      },
      {
         "route_id":"70A",
         "route_name":"70A"
      },
      {
         "route_id":"71",
         "route_name":"71"
      },
      {
         "route_id":"72",
         "route_name":"72"
      },
      {
         "route_hide":"true",
         "route_id":"725",
         "route_name":"72/75"
      },
      {
         "route_id":"73",
         "route_name":"73"
      },
      {
         "route_id":"74",
         "route_name":"74"
      },
      {
         "route_id":"75",
         "route_name":"75"
      },
      {
         "route_id":"76",
         "route_name":"76"
      },
      {
         "route_id":"77",
         "route_name":"77"
      },
      {
         "route_id":"78",
         "route_name":"78"
      },
      {
         "route_id":"79",
         "route_name":"79"
      },
      {
         "route_id":"80",
         "route_name":"80"
      },
      {
         "route_id":"83",
         "route_name":"83"
      },
      {
         "route_id":"84",
         "route_name":"84"
      },
      {
         "route_id":"85",
         "route_name":"85"
      },
      {
         "route_id":"86",
         "route_name":"86"
      },
      {
         "route_id":"87",
         "route_name":"87"
      },
      {
         "route_id":"88",
         "route_name":"88"
      },
      {
         "route_id":"89",
         "route_name":"89"
      },
      {
         "route_hide":"true",
         "route_id":"8993",
         "route_name":"89/93"
      },
      {
         "route_id":"90",
         "route_name":"90"
      },
      {
         "route_id":"91",
         "route_name":"91"
      },
      {
         "route_id":"92",
         "route_name":"92"
      },
      {
         "route_id":"93",
         "route_name":"93"
      },
      {
         "route_id":"94",
         "route_name":"94"
      },
      {
         "route_id":"95",
         "route_name":"95"
      },
      {
         "route_id":"96",
         "route_name":"96"
      },
      {
         "route_id":"97",
         "route_name":"97"
      },
      {
         "route_id":"99",
         "route_name":"99"
      },
      {
         "route_id":"100",
         "route_name":"100"
      },
      {
         "route_id":"101",
         "route_name":"101"
      },
      {
         "route_id":"104",
         "route_name":"104"
      },
      {
         "route_id":"105",
         "route_name":"105"
      },
      {
         "route_id":"106",
         "route_name":"106"
      },
      {
         "route_id":"108",
         "route_name":"108"
      },
      {
         "route_id":"109",
         "route_name":"109"
      },
      {
         "route_id":"110",
         "route_name":"110"
      },
      {
         "route_id":"111",
         "route_name":"111"
      },
      {
         "route_id":"112",
         "route_name":"112"
      },
      {
         "route_id":"114",
         "route_name":"114"
      },
      {
         "route_id":"116",
         "route_name":"116"
      },
      {
         "route_hide":"true",
         "route_id":"116117",
         "route_name":"116/117"
      },
      {
         "route_id":"117",
         "route_name":"117"
      },
      {
         "route_id":"119",
         "route_name":"119"
      },
      {
         "route_id":"120",
         "route_name":"120"
      },
      {
         "route_id":"121",
         "route_name":"121"
      },
      {
         "route_id":"131",
         "route_name":"131"
      },
      {
         "route_id":"132",
         "route_name":"132"
      },
      {
         "route_id":"134",
         "route_name":"134"
      },
      {
         "route_id":"136",
         "route_name":"136"
      },
      {
         "route_id":"137",
         "route_name":"137"
      },
      {
         "route_id":"170",
         "route_name":"170"
      },
      {
         "route_id":"171",
         "route_name":"171"
      },
      {
         "route_id":"195",
         "route_name":"195"
      },
      {
         "route_id":"201",
         "route_name":"201"
      },
      {
         "route_id":"202",
         "route_name":"202"
      },
      {
         "route_id":"210",
         "route_name":"210"
      },
      {
         "route_id":"211",
         "route_name":"211"
      },
      {
         "route_id":"212",
         "route_name":"212"
      },
      {
         "route_id":"214",
         "route_name":"214"
      },
      {
         "route_hide":"true",
         "route_id":"214216",
         "route_name":"214/216"
      },
      {
         "route_id":"215",
         "route_name":"215"
      },
      {
         "route_id":"216",
         "route_name":"216"
      },
      {
         "route_id":"217",
         "route_name":"217"
      },
      {
         "route_id":"220",
         "route_name":"220"
      },
      {
         "route_id":"221",
         "route_name":"221"
      },
      {
         "route_id":"222",
         "route_name":"222"
      },
      {
         "route_id":"225",
         "route_name":"225"
      },
      {
         "route_id":"230",
         "route_name":"230"
      },
      {
         "route_id":"236",
         "route_name":"236"
      },
      {
         "route_id":"238",
         "route_name":"238"
      },
      {
         "route_id":"240",
         "route_name":"240"
      },
      {
         "route_id":"245",
         "route_name":"245"
      },
      {
         "route_id":"325",
         "route_name":"325"
      },
      {
         "route_id":"326",
         "route_name":"326"
      },
      {
         "route_id":"350",
         "route_name":"350"
      },
      {
         "route_id":"351",
         "route_name":"351"
      },
      {
         "route_id":"352",
         "route_name":"352"
      },
      {
         "route_id":"354",
         "route_name":"354"
      },
      {
         "route_id":"411",
         "route_name":"411"
      },
      {
         "route_id":"424",
         "route_name":"424"
      },
      {
         "route_id":"426",
         "route_name":"426"
      },
      {
         "route_id":"428",
         "route_name":"428"
      },
      {
         "route_id":"429",
         "route_name":"429"
      },
      {
         "route_id":"430",
         "route_name":"430"
      },
      {
         "route_id":"431",
         "route_name":"431"
      },
      {
         "route_id":"434",
         "route_name":"434"
      },
      {
         "route_id":"435",
         "route_name":"435"
      },
      {
         "route_id":"436",
         "route_name":"436"
      },
      {
         "route_id":"439",
         "route_name":"439"
      },
      {
         "route_id":"441",
         "route_name":"441"
      },
      {
         "route_hide":"true",
         "route_id":"441442",
         "route_name":"441/442"
      },
      {
         "route_id":"442",
         "route_name":"442"
      },
      {
         "route_id":"448",
         "route_name":"448"
      },
      {
         "route_id":"449",
         "route_name":"449"
      },
      {
         "route_id":"450",
         "route_name":"450"
      },
      {
         "route_id":"451",
         "route_name":"451"
      },
      {
         "route_id":"455",
         "route_name":"455"
      },
      {
         "route_id":"456",
         "route_name":"456"
      },
      {
         "route_id":"459",
         "route_name":"459"
      },
      {
         "route_id":"465",
         "route_name":"465"
      },
      {
         "route_id":"501",
         "route_name":"501"
      },
      {
         "route_id":"502",
         "route_name":"502"
      },
      {
         "route_id":"503",
         "route_name":"503"
      },
      {
         "route_id":"504",
         "route_name":"504"
      },
      {
         "route_id":"505",
         "route_name":"505"
      },
      {
         "route_id":"553",
         "route_name":"553"
      },
      {
         "route_id":"554",
         "route_name":"554"
      },
      {
         "route_id":"556",
         "route_name":"556"
      },
      {
         "route_id":"558",
         "route_name":"558"
      },
      {
         "route_id":"710",
         "route_name":"710"
      },
      {
         "route_id":"712",
         "route_name":"712"
      },
      {
         "route_id":"713",
         "route_name":"713"
      },
      {
         "route_id":"714",
         "route_name":"714"
      },
      {
         "route_id":"716",
         "route_name":"716"
      },
      {
         "route_id":"9701",
         "route_name":"9701"
      },
      {
         "route_id":"9702",
         "route_name":"9702"
      },
      {
         "route_id":"9703",
         "route_name":"9703"
      }
   ],
   "route_type":"3"
}

var stops = {
   "stop":[
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"5090",
      "stop_lat":"42.336679",
      "stop_lon":"-71.070973",
      "stop_name":"88 E Newton St",
      "stop_order":"1"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"5089",
      "stop_lat":"42.33556",
      "stop_lon":"-71.072264",
      "stop_name":"91 E Concord St",
      "stop_order":"2"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"58",
      "stop_lat":"42.334948",
      "stop_lon":"-71.074931",
      "stop_name":"Massachusetts Ave @ Harrison Ave",
      "stop_order":"3"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"10590",
      "stop_lat":"42.336621",
      "stop_lon":"-71.076956",
      "stop_name":"Massachusetts Ave @ Washington St",
      "stop_order":"4"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"87",
      "stop_lat":"42.339459",
      "stop_lon":"-71.080362",
      "stop_name":"Massachusetts Ave @ Tremont St",
      "stop_order":"5"
   },
   {
      "parent_station":"place-masta",
      "parent_station_name":"Massachusetts Ave.",
      "stop_id":"188",
      "stop_lat":"42.341512",
      "stop_lon":"-71.083423",
      "stop_name":"Massachusetts Ave @ Massachusetts Ave Station",
      "stop_order":"6"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"89",
      "stop_lat":"42.342303",
      "stop_lon":"-71.084121",
      "stop_name":"Massachusetts Ave @ St Botolph St",
      "stop_order":"7"
   },
   {
      "parent_station":"place-hymnl",
      "parent_station_name":"Hynes Convention Center",
      "stop_id":"93",
      "stop_lat":"42.347888",
      "stop_lon":"-71.087903",
      "stop_name":"Massachusetts Ave @ Newbury St",
      "stop_order":"8"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"95",
      "stop_lat":"42.350773",
      "stop_lon":"-71.089334",
      "stop_name":"Massachusetts Ave @ Beacon St",
      "stop_order":"9"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"97",
      "stop_lat":"42.359183",
      "stop_lon":"-71.093543",
      "stop_name":"77 Massachusetts Ave",
      "stop_order":"10"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"101",
      "stop_lat":"42.362988",
      "stop_lon":"-71.099486",
      "stop_name":"Massachusetts Ave @ Sidney St",
      "stop_order":"11"
   },
   {
      "parent_station":"",
      "parent_station_name":"",
      "stop_id":"1060",
      "stop_lat":"42.365114",
      "stop_lon":"-71.104311",
      "stop_name":"Magazine St @ Green St",
      "stop_order":"12"
   }
]
};

// routes.route.forEach(function(elem) {
//     console.log(elem["route_name"])
// })

stops.stop.forEach(function(elem) {
    var stopName = elem["stop_name"];
    if (stopName.indexOf("@") >= 0) {
        console.log(stopName.replace("@", "and").replace("-", "").replace("+", ""));
    }
    if (stopName.indexOf("opp") >= 0) {
        console.log(stopName.replace("opp", "and").replace("-", "").replace("+", ""));
    }
    stopName = stopName.replace("@", "at").replace("opp", "opposite").replace("-", "").replace("+", "");
    console.log(stopName);
})